1. Tentukan Library


In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score


2. Load Dataset

In [3]:
anemia_dataset = pd.read_csv('anemia.csv')

In [4]:
anemia_dataset.head()

Gender  Hemoglobin   MCH  MCHC   MCV  Result
0       1        14.9  22.7  29.1  83.7       0
1       0        15.9  25.4  28.3  72.0       0
2       0         9.0  21.5  29.6  71.2       1
3       0        14.9  16.0  31.4  87.5       0
4       1        14.7  22.0  28.2  99.5       0

In [5]:
anemia_dataset.shape

(1421, 6)

In [6]:
anemia_dataset['Result'].value_counts()

0    801
1    620
Name: Result, dtype: int64

In [7]:
#Memisahkana data dan label
X = anemia_dataset.drop(columns='Result', axis=1)
Y = anemia_dataset['Result']

In [8]:
print(X)

      Gender  Hemoglobin   MCH  MCHC   MCV
0          1        14.9  22.7  29.1  83.7
1          0        15.9  25.4  28.3  72.0
2          0         9.0  21.5  29.6  71.2
3          0        14.9  16.0  31.4  87.5
4          1        14.7  22.0  28.2  99.5
...      ...         ...   ...   ...   ...
1416       0        10.6  25.4  28.2  82.9
1417       1        12.1  28.3  30.4  86.9
1418       1        13.1  17.7  28.1  80.7
1419       0        14.3  16.2  29.5  95.2
1420       0        11.8  21.2  28.4  98.1

[1421 rows x 5 columns]


In [9]:
print(Y)

0       0
1       0
2       1
3       0
4       0
       ..
1416    1
1417    1
1418    1
1419    0
1420    1
Name: Result, Length: 1421, dtype: int64


3. Standarisasi

In [10]:
scaler =  StandardScaler()

In [11]:
scaler.fit(X)

StandardScaler()

In [12]:
standarized_data = scaler.transform(X)

In [13]:
print(standarized_data)

[[ 0.95930718  0.75348274 -0.05182232 -0.82207061 -0.18932081]
 [-1.04241896  1.26010665  0.62862494 -1.39333406 -1.40385665]
 [-1.04241896 -2.23559834 -0.35424332 -0.46503096 -1.48690183]
 ...
 [ 0.95930718 -0.1584403  -1.31190984 -1.53614992 -0.50074026]
 [-1.04241896  0.44950839 -1.68993609 -0.53643889  1.00445372]
 [-1.04241896 -0.81705139 -0.42984857 -1.32192613  1.30549252]]


In [14]:
X = standarized_data
Y = anemia_dataset['Result']

In [15]:
print(X)
print(Y)


[[ 0.95930718  0.75348274 -0.05182232 -0.82207061 -0.18932081]
 [-1.04241896  1.26010665  0.62862494 -1.39333406 -1.40385665]
 [-1.04241896 -2.23559834 -0.35424332 -0.46503096 -1.48690183]
 ...
 [ 0.95930718 -0.1584403  -1.31190984 -1.53614992 -0.50074026]
 [-1.04241896  0.44950839 -1.68993609 -0.53643889  1.00445372]
 [-1.04241896 -0.81705139 -0.42984857 -1.32192613  1.30549252]]
0       0
1       0
2       1
3       0
4       0
       ..
1416    1
1417    1
1418    1
1419    0
1420    1
Name: Result, Length: 1421, dtype: int64


4. Pisahkan Data Training dan Data Testing

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, stratify=Y, random_state=2)

In [17]:
print(X.shape, X_train.shape, X_test.shape)

(1421, 5) (1136, 5) (285, 5)


5. Membuat data latih menggunakan algo SVM


In [21]:
classifier = svm.SVC(kernel='linear')

In [22]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

6. Buat Model evaluasi untuk mengukur tingkat akurasi

In [23]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [24]:
 print('Akurasi data traing adalah = ', training_data_accuracy)

Akurasi data traing adalah =  0.9911971830985915


In [25]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [26]:
print('Akurasi data testing adalah = ', test_data_accuracy)

Akurasi data testing adalah =  0.9789473684210527


7. Membuat Model Prediksi

In [29]:
input_data = (1, 14.9 ,22.7 ,29.1 ,83.7)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] ==0):
    print('pasien tidak terkena Anemia') 
else :
    print('pasien Terkena Anemia')

 

[[ 0.95930718  0.75348274 -0.05182232 -0.82207061 -0.18932081]]
[0]
pasien tidak terkena Anemia


C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [32]:
input_data = (0, 9, 21.5, 29.6, 71.2)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] ==0):
    print('pasien tidak terkena Anemia') 
else :
    print('pasien Terkena Anemia')

[[-1.04241896 -2.23559834 -0.35424332 -0.46503096 -1.48690183]]
[1]
pasien Terkena Anemia


C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


8. Simpan Model

In [30]:
import pickle

In [31]:
filename = 'anemia_model.sav'
pickle.dump(classifier, open(filename,'wb'))